### ISSUE TITLE
error: undefined symbol: cpuinfo_emscripten_init

### ISSUE THREAD

**Issue by DoDoENT** [pytorch/cpuinfo#34]
When trying to use CPUInfo on Emscripten, I get the following linker error:

```
error: undefined symbol: cpuinfo_emscripten_init
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
```

Indeed, no file in this repository provides an implementation for function `cpuinfo_emscripten_init`.

I've seen that XNNPACK guys contributed this function, but where is the implementation? I've seen that their [bazel file](https://github.com/google/XNNPACK/blob/master/third_party/cpuinfo.BUILD#L59) mentions some `src/emscripten/init.c` file, but I cannot find it (even their patch file does not contain it).

**Comment by AshkanAliabadi** [comment]
@Maratyszcza

**Comment by Maratyszcza** [comment]
I'll include `src/emscripten/init.c` in the next patch, but keep in mind that it is not sufficient to build XNNPACK for WebAssembly with CMake

**Comment by DoDoENT** [comment]
I am not trying to build XNNPACK for WebAssembly. I am using cpuinfo in a different project.

**Comment by Maratyszcza** [comment]
Keep in mind that most information about CPU is not exposed in browser environment, so cpuinfo mostly guesstimates this data.

**Comment by DoDoENT** [comment]
Of course. Even though its guesstimates, it's still better than nothing.

**Comment by iliagrigorevdev** [comment]
It looks like file `src/emscripten/init.c` cannot be added because `CPUINFO_SUPPORTED_PLATFORM` is false for build with Emscripten, which results to `error: undefined symbol: cpuinfo_emscripten_init`

**Comment by iliagrigorevdev** [comment]
I made a patch to solve this problem, but I do not know exactly what side effects it can lead.

Patch: [undef_symb_emsc.txt](https://github.com/pytorch/cpuinfo/files/6720132/undef_symb_emsc.txt)

**Comment by ScottTodd** [comment]
This issue is still occurring with CMake. The suggested patch to include `Emscripten` here appears to work for my usage in a different downstream project: https://github.com/pytorch/cpuinfo/blob/85e931e36af24a3ec73b146b9fe8423b4b2a67db/CMakeLists.txt#L80-L85
(so `CPUINFO_SUPPORTED_PLATFORM` remains `TRUE`)

Are there other changes that would be needed to accept that patch? Maybe some test updates or adding "Emscripten" here too?

https://github.com/pytorch/cpuinfo/blob/85e931e36af24a3ec73b146b9fe8423b4b2a67db/README.md#L11-L12
