### ISSUE TITLE
pytorch build fails: __NR_getcpu undeclared, a possible fix included

### ISSUE THREAD

**Issue by pearu** [pytorch/cpuinfo#36]
The current master branch of pytorch fails to build with the following error:
```
[86/3487] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o
FAILED: confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o 
/home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/x86_64-conda_cos6-linux-gnu-cc -DCPUINFO_LOG_LEVEL=2 -DTH_BLAS_MKL -D_GNU_SOURCE=1 -I../third_party/cpuinfo/src -I../third_party/cpuinfo/include -I../third_party/cpuinfo/deps/clog/include -isystem ../third_party/protobuf/src -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/pearu/miniconda3/envs/pytorch-cuda-dev/include -I/usr/local/cuda-10.1.243/include -L/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib -O3 -DNDEBUG -fPIC   -std=c99 -MD -MT confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o -MF confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o.d -o confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/api.c.o   -c ../third_party/cpuinfo/src/api.c
In file included from ../third_party/cpuinfo/src/cpuinfo/internal-api.h:11:0,
                 from ../third_party/cpuinfo/src/api.c:5:
../third_party/cpuinfo/src/api.c: In function 'cpuinfo_get_current_processor':
../third_party/cpuinfo/src/api.c:316:31: error: '__NR_getcpu' undeclared (first use in this function); did you mean '__NR_getcwd'?
   if CPUINFO_UNLIKELY(syscall(__NR_getcpu, &cpu, NULL, NULL) != 0) {
                               ^
../third_party/cpuinfo/src/cpuinfo/common.h:16:59: note: in definition of macro 'CPUINFO_UNLIKELY'
  #define CPUINFO_UNLIKELY(condition) (__builtin_expect(!!(condition), 0))
                                                           ^~~~~~~~~
../third_party/cpuinfo/src/api.c:316:31: note: each undeclared identifier is reported only once for each function it appears in
   if CPUINFO_UNLIKELY(syscall(__NR_getcpu, &cpu, NULL, NULL) != 0) {
                               ^
../third_party/cpuinfo/src/cpuinfo/common.h:16:59: note: in definition of macro 'CPUINFO_UNLIKELY'
  #define CPUINFO_UNLIKELY(condition) (__builtin_expect(!!(condition), 0))
                                                           ^~~~~~~~~
../third_party/cpuinfo/src/api.c: In function 'cpuinfo_get_current_core':
../third_party/cpuinfo/src/api.c:334:31: error: '__NR_getcpu' undeclared (first use in this function); did you mean '__NR_getcwd'?
   if CPUINFO_UNLIKELY(syscall(__NR_getcpu, &cpu, NULL, NULL) != 0) {
                               ^
../third_party/cpuinfo/src/cpuinfo/common.h:16:59: note: in definition of macro 'CPUINFO_UNLIKELY'
  #define CPUINFO_UNLIKELY(condition) (__builtin_expect(!!(condition), 0))
```

Applying
```
$ git diff
diff --git a/src/api.c b/src/api.c
index 0cc5d4e..5903edf 100644
--- a/src/api.c
+++ b/src/api.c
@@ -10,6 +10,7 @@
 
        #include <unistd.h>
        #include <sys/syscall.h>
+        #include <asm-generic/unistd.h>
 #endif
```
fixes the build issue.

**Comment by bryan-lunt** [comment]
Yeah, I had this problem too.
Why can't the code be written to use the <sched.h> capabilities?

http://man7.org/linux/man-pages/man3/sched_getcpu.3.html

**Comment by rgommers** [comment]
> Shouldn't either `unistd.h` or `sys/syscall.h` automatically get the right `asm-*/unistd.h`? I think there's a bigger issue if you have to include it directly.

The reason is that conda compilers are behind or modified. Current conda `x86_64-conda_cos6-linux-gnu/sysroot/usr/include/asm/unistd_64.h` missed `__NR_getcpu`, instead it has:
```
#define __IGNORE_getcpu         /* implemented as a vsyscall */
```
while for me `/usr/include/asm/unistd_64.h`
```
#define __NR_getcpu 309
```

Searching the whole `asm` dir inside the conda sysroot:
```
./unistd_32.h:
  326 : #define __NR_getcpu             318
./unistd_64.h:
  627 : #define __IGNORE_getcpu         /* implemented as a vsyscall */
./vsyscall.h:
    7 :         __NR_vgetcpu,
```

> Why can't the code be written to use the <sched.h> capabilities?

This came in recently in commit dcf8e1896b8b0. @AshkanAliabadi could you comment?

**Comment by bryan-lunt** [comment]
So the thing with supercomputers is that they have to stay very stable, and essentially stick with the same major version of things forever after install.

In particular, the kernels end up two or more major versions out of date.

The more POSIX-y and less LINUX-y things can be, the happier I would be.

http://man7.org/linux/man-pages/man7/sched.7.html

**Comment by AshkanAliabadi** [comment]
Hey everyone.  Thanks for reporting this and apologies for the problem this has caused.  As for the why of this change, we needed to keep cpuinfo updated to support the latest processors.  There is unfortunately always this tension between stability on one hand, and introducing new functionality as new features can potentially bring about instability by their very nature.

More specifically, we added this change since this updated version of cpuinfo is required by XNNPACK to build properly - XNNPACK itself being a high performance neural network inference library we are integrating into PyTorch mobile, in turn bringing a significant performance boost to PyTroch on Android and iOS.  The tradeoff then, was to whether forego the performance benefit XNNPACK brings to PT-M in favor of stability, or instead lean on the side of performance at the cost of rocking the boat a bit, and we felt more performance on Android and iOS would be something our larger community would appreciate more than the potential issues - potential at the time, actual at this point :) - that this change could cause.  We made sure that these changes pass the PyTorch CI, so at least on any of the 50+ PyTorch CI jobs we have targeting different platforms and compilers, this didn't raise any issue.

So having explained the why of the change, I would be more than happy to merge the fix @pearu posted above and update PyTorch accordingly.  Does that change work for everyone?

**Comment by rgommers** [comment]
>  would be more than happy to merge the fix @pearu posted above and update PyTorch accordingly. Does that change work for everyone?

That doesn't look quite right, because it's conda-specific. I assume for newer kernels you'd want to get `asm` rather than `asm-generic`.

Just googling `__NR_getcpu` it looks like it should be wrapped in an `ifdef`. The only uses here and in XNNPACK are anyway in an optional linux-only `_UNLIKELY` macro, so just using
```
if defined(__linux__) && defined(__NR_getcpu)
```
instead of 
```
if defined(__linux__) 
```
should make things more robust here.

@bryan-lunt it seems like `sched_getcpu` isn't reliable for old kernels (https://stackoverflow.com/questions/36934736/is-sched-getcpu-reliable-on-linux), so doesn't look like that helps.

**Comment by AshkanAliabadi** [comment]
PR: https://github.com/pytorch/cpuinfo/pull/37

@Maratyszcza To answer Bryan's question, do you guys have any plans to rewrite the code with sched.h?

**Comment by pearu** [comment]
> That doesn't look quite right, because it's conda-specific. I assume for newer kernels you'd want to get `asm` rather than `asm-generic`.

I cannot confirm that this is conda-specific. For instance, in my Ubuntu 18.04 box `/usr/include/asm-generic/unistd.h` exists and defines `__NR_getcpu`.

However, wrapping `#include <asm-generic/unistd.h>` inside `#if defined(__NR_getcpu)` block seems reasonable.

**Comment by Maratyszcza** [comment]
`sched_getcpu` is not portable either (it is a GLibC extension), and it adds overhead compared to direct syscall, so no plans to revert to it.

**Comment by rgommers** [comment]
@bryan-lunt what kernel version do you actually have, and does gh-37 fix things for you?

**Comment by bryan-lunt** [comment]
At least the headnode has "3.0.101-0.47.106.59.1.17833.1.PTF-default"

**Comment by rgommers** [comment]
gh-37 is merged, can we close this?
